"""Fish completion file generator.

Outputs fish completion files in the format fish expects under
~/.cache/fish/generated_completions/<command>.fish

Example output for `tar`:

    complete -c tar -s c -l create -d 'Create a new archive'
    complete -c tar -s x -l extract -d 'Extract files from an archive'
    complete -c tar -s f -l file -r -d 'Use archive file'
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from krill.catalog import Catalog


def _escape_fish(value: str) -> str:
    """Escape a string for safe inclusion in a fish completion file."""
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _generate_option_line(command: str, opt: dict[str, Any]) -> str:
    """Generate a single `complete -c ...` line for one option."""
    parts = [f"complete -c {command}"]

    short = opt.get("short", "")
    long = opt.get("long", "")
    typ = opt.get("type", "boolean")
    desc = opt.get("description", "")
    required = opt.get("required", False)

    # Skip invalid short flags (fish treats # as comment, etc.)
    if short and not re.match(r'^-[a-zA-Z0-9]$', short):
        short = ""

    if short:
        parts.append(f"-s {short.lstrip('-')}")
    if long:
        parts.append(f"-l {long.lstrip('-')}")
    if typ != "boolean":
        parts.append("-r")  # requires argument
    if desc:
        parts.append(f"-d '{_escape_fish(desc)}'")

    return " ".join(parts)


def generate_completion_file(
    command: str,
    options: list[dict[str, Any]],
    subcommands: list[dict[str, Any]] | None = None,
) -> str:
    """Generate a complete fish completion file content for a command.

    Args:
        command: The command name (e.g., "tar", "git")
        options: List of option dicts with keys: short, long, type, description
        subcommands: Optional list of subcommand dicts with keys: name, description

    Returns:
        Fish completion file content as a string.
    """
    lines = [f"# Generated by krill — do not edit by hand\n"]

    # Options (flags)
    for opt in options:
        if opt.get("short") or opt.get("long"):
            lines.append(_generate_option_line(command, opt))

    # Subcommands
    if subcommands:
        sub_names = [s["name"] for s in subcommands]
        descs = " ".join(
            f"{s['name']}\\t{_escape_fish(s.get('description', ''))}"
            for s in subcommands
        )
        lines.append(f"complete -c {command} -n 'not __fish_seen_subcommand_from {' '.join(sub_names)}' -a '{descs}' -f")
        # Prevent file completions for subcommands that don't take files
        lines.append(f"complete -c {command} -f")

    return "\n".join(lines) + "\n"


def write_completion_files(
    catalog: Catalog,
    output_dir: str | Path,
    *,
    overwrite: bool = False,
    commands: list[str] | None = None,
) -> list[Path]:
    """Generate and write completion files for all catalogued commands.

    Args:
        catalog: The catalog database.
        output_dir: Directory to write .fish files to (typically
                    ~/.config/fish/completions/).
        overwrite: If False (default), skip files that already exist.
        commands: Specific commands to generate. If None, generates for all.

    Returns:
        List of written file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    skipped: list[str] = []

    # If no specific commands, get all from catalog
    if commands is None:
        commands = catalog.list_all_commands()

    for cmd in commands:
        filepath = output_dir / f"{cmd}.fish"

        # Skip existing files unless --force
        if not overwrite and filepath.exists():
            skipped.append(cmd)
            continue

        opts = catalog.get_options(cmd)
        subs = catalog.get_subcommands(cmd)
        if opts is None:
            continue

        content = generate_completion_file(cmd, opts, subs)
        filepath.write_text(content)
        written.append(filepath)

    if skipped:
        import sys
        print(f"Skipped {len(skipped)} existing files (use --force to overwrite)", file=sys.stderr)

    return written


def generate_fish_update_script(
    catalog: Catalog,
    output_dir: str | Path,
) -> str:
    """Generate a shell script that replaces fish_update_completions.

    This script is intended to be called instead of fish's built-in
    `create_manpage_completions.py`. It queries the krill catalog and
    writes completion files.
    """
    return f"""#!/usr/bin/env python3
\"\"\"krill completion generator — drop-in replacement for fish's create_manpage_completions.py\"\"\"
import sys
sys.path.insert(0, '{Path(__file__).parent}')

from krill.catalog import Catalog
from krill.generator import write_completion_files

catalog = Catalog()
written = write_completion_files(catalog, '{output_dir}')
print(f"Generated {{len(written)}} completion files", file=sys.stderr)
"""